kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${{ values.repoName }}
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.repoName }}
  template:
    metadata:
      labels:
        app: ${{ values.repoName }}
        app.kubernetes.io/component: backstage
        backstage.io/kubernetes-id: ${{ values.repoName }}
    spec:
      containers:
        - name: ${{ values.repoName }}
          image: ${{ values.imageRepository }}/${{ values.imageUrl }}
          ports:
            - name: http-${{ values.port }}
              containerPort: ${{ values.port }}
              protocol: TCP