apiVersion: v1
kind: Service
metadata:
  name: ${{ values.appName }}
  labels:
    backstage.io/kubernetes-id: ${{ values.appName }}
    app: ${{ values.appName }}
spec:
  type: ClusterIP
  selector:
    app: ${{ values.appName }}
  ports:
    - port: 8080
      protocol: TCP
      name: http